### ISSUE TITLE
The types provided in the NPM package seem wrong

### ISSUE THREAD

**Issue by Lucas-C** [thepassle/module-graph#12]
Hi.

I am not able to execute your basic demo script:
https://github.com/thepassle/module-graph?tab=readme-ov-file#typescript

I'm using NodeJS v18.19.1 with `typescript@4.8.4` and `ts-node@10.9.1` and trying to execute your script with:
```
$ npx ts-node module-graph.ts
./node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module ./node_modules/@thepassle/module-graph/index.js from ./module-graph.ts not supported.
Instead change the require of index.js in ./module-graph.ts to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (./node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (./module-graph.ts:7:24)
    at m._compile (./node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (./node_modules/ts-node/dist/index.js:859:16)
    at phase4 (./node_modules/ts-node/dist/bin.js:466:20)
    at bootstrap (./node_modules/ts-node/dist/bin.js:54:12)
    at main (./node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (./node_modules/ts-node/dist/bin.js:579:5) {
  code: 'ERR_REQUIRE_ESM'
}
```

Based on the output of this online checker, there may be type declarations missing:
https://arethetypeswrong.github.io/?p=%40thepassle%2Fmodule-graph%400.7.5

**Comment by Lucas-C** [comment]
OK so in my case the solution was to:
1. rename `module-graph.ts` into `module-graph.mjs`
2. Invoke the script with: `node module-graph.mjs`
